name: SonarCloud Analysis with Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  sonarcloud:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonar con todo el historial para mejor análisis

      # Configurar Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      # Encontrar y compilar archivos Java
      - name: Prepare Java environment
        run: |
          mkdir -p target/classes
          echo "Compilando archivos Java..."
          # Encuentra todos los archivos Java y los compila en target/classes
          find . -name "*.java" -type f | xargs -I {} echo "Compilando: {}"
          find . -name "*.java" -type f -exec javac -d target/classes {} \; || echo "Advertencia: Errores de compilación, pero continuando"
          echo "Archivos compilados:"
          find target/classes -type f | wc -l
          
      # Crear directorio para dependencias (para evitar errores)
      - name: Create dependency directory
        run: mkdir -p target/dependency
          
      # SonarCloud scan con configuración para Java
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
